services:
  postgres:
    image: postgres
    ports:
      - 5477:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata: